name: ttoklip_manager
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  dart_code_metrics: ^5.7.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  flutter_svg: ^2.0.9 #svg 파일 쓰기
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  retrofit: ^4.0.3
  get_it: ^7.6.6
  logger: ^2.0.2+1 #Exception 공통화
  mocktail: ^1.0.2 #Unit test
  bloc_concurrency: ^0.2.3 #스롯토링 (이벤트를 조작) / 안하면 한번에 많은 호출이됨
  stream_transform: ^2.1.0 # ''
  injectable: ^2.3.2 # get_it .inject
  intl: #int -> string 포맷

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/fonts/

